### ISSUE TITLE
Lewis Crafting Table Texture

### ISSUE THREAD

**Issue by Robin-Dillen** [ScicraftLearn/Scicraft#102]
Can someone make a Lewis crafting table texture?

**Comment by RandyParedis** [comment]
They were already on the Google Drive, but here they are again :)

Texture:
![lewis_crafting_table](https://user-images.githubusercontent.com/25817922/158016697-8d9b3067-069e-4aaa-b248-590abaaeed22.png)

Model:
https://drive.google.com/file/d/1Z8MPLa_95hef7bNU3PI0koIIPH_d5xmS/view?usp=sharing

Let me know if you need anything else.
