### ISSUE TITLE
Lewis crafting table: Open vraag: Erlenmeyer in outputslot

### ISSUE THREAD

**Issue by MajaVerstraeten** [ScicraftLearn/Scicraft#125]
Gassen en vloeistoffen zitten in een Erlenmeyer.
Wordt de Erlenmeyer gratis en voor niets meegegeven in het output slot?

Of moet de speler de Erlenmeyer aanleveren?
Of wordt de Lewis crafting table gemaakt volgens een recipe dat meerdere Erlenmeyers bevat?

**Comment by BillyVanhove** [comment]
Er is een outputslot voorzien voor erlenmeyers en dit slot wordt permanent getoond.
