### ISSUE TITLE
Throwable Proton and Neutron 

### ISSUE THREAD

**Issue by JoeyDP** [ScicraftLearn/Scicraft#16]
Make protons and neutrons throwable as well. They can have the same flying behaviour for now, although in the future we will likely want to define different speeds and impact of gravity for example. Keep this in mind.

If applicable, an intermediate class "AtomComponent" can be created for the items and/or entities that need to be made. Perhaps the more physics oriented people also have a better name for this @BertJorissen?

**Comment by MajaVerstraeten** [comment]
Agree on the "subatomic" name!

But I think the e/m experiment has nothing to do with gravity but with the orbit in a magnetic field
https://wanda.fiu.edu/boeglinw/courses/Modern_lab_manual3/em_ratio.html

**Comment by MajaVerstraeten** [comment]
I feel VERY inclined to implement magnets.
And then to cause the motion of charged particles with a numerical approach. i.e. a particles determines where it will go in the next tick, based on its vicinity to charges and magnets, mass and current speed.

We can even visualise magnetic fields with little 3D compasses (essentially an arow that can have many orientations within a block).

**Comment by RandyParedis** [comment]
Maybe magnets are a little bit off-topic, but it would be really cool to have those. They might also interact with the in-game compass, or we could have Magnetite Ore (that can be crafted into magnets/magnet blocks using iron?)
Not sure how the magnetic fields can be done practically, but a visualisation could be really nice.
