### ISSUE TITLE
Scientific Villager: Textures

### ISSUE THREAD

**Issue by RobbeNooyens** [ScicraftLearn/Scicraft#26]
What are scientific villagers without their typical lab coat? The default villagers are too .. default? So that's why we will also need new villager textures.

### Requirements
- Create at least 3 new villager textures

**Comment by RandyParedis** [comment]
I looked at how villagers are skinned in Minecraft and they apparently have 4 layers (I just learned about this): Villager in Underwear, Biome Clothes, Profession Outfit and Level Notch. They are layered in this order in the default game. I guess this reduces the amount of copy-pasting between villager textures. In the code, is it possible to only define the Profession, or do you need all of them?

And what exactly do you mean with 3 textures? Do you want to have a randomized texture, or do you want textures for all biomes and levels?

**Comment by RandyParedis** [comment]
Using the layered approach from Minecraft, you can still keep the "biome"-mentality. Here is what the Scientist-Villagers might look like. Feedback welcome!

![2021-12-03_19 49 59](https://user-images.githubusercontent.com/25817922/144659284-6dacdb89-2d7c-44e2-979a-5b4e762c5a15.png)
![2021-12-03_19 49 24](https://user-images.githubusercontent.com/25817922/144659287-d774d32f-1b43-4dcf-8154-45c6781f3568.png)

And the skin file is here:
![scientist](https://user-images.githubusercontent.com/25817922/144659546-bb4e031e-3bef-4141-8194-41adb6e50df7.png)
