### ISSUE TITLE
Entropy Creeper

### ISSUE THREAD

**Issue by JoeyDP** [ScicraftLearn/Scicraft#3]
Though we are still figuring out the best way to bring educative concepts to Minecraft, one of the more random additions from ElementaryCraft can already be ported: the Entropy Mob.

Essentially this mob is simply a re-skinned version of a Creeper (skin available from ElementaryCraft) that, instead of causing an explosion when detonated, causes the blocks around it to be shuffled randomly.

### Specification
- The Entropy Creeper behaves exactly like a Creeper, with the exceptions listed below.
- When the Entropy Creeper detonates, it randomly swaps the blocks within a cuboid of radius 5 (to be refined).

### Suggested Implementation Steps
- [x] Read up on adding entities with Fabric:
  - https://fabricmc.net/wiki/tutorial:entity
  - https://fabricmc.net/wiki/tutorial:spawn_egg
- [x] Inspect the Minecraft source code of the Creeper
- [x] Add a new Mob based on the Creeper (as extension or by copying it)
- [x] Style the new mob with the textures from ElementaryCraft
- [x] Implement the custom action instead of the explosion
- [ ] Test whether everything works with a separate server and client
- [x] Submit and document pull request for review
- [ ] #8
  - If the player is in the radius, they also get teleported randomly within a specified range
  - Animate the swapping of blocks (don't move all at the same time, but do some moving over the next x ticks.
  - A cuboid radius is quite structured which goes against the nature of this mob. Change this to a more chaotic shape, similar to that of an explosion.
  - Add a custom sound to the shuffling and perhaps also to replace the 'sizzling' of a Creeper to warm the player.

**Comment by IneMEGAmaxi** [comment]
Latest Entropy Creeper texture and Photoshop file (.psd is not supported by Github, so it is added in the .zip)
[entropyMOB.zip](https://github.com/ScicraftLearn/Scicraft/files/7613623/entropyMOB.zip)
![entropyMOB](https://user-images.githubusercontent.com/29948516/143770326-d0b87f2b-9653-48ef-af31-fb62c14824da.png)

**Comment by pixar02** [comment]
![2021-11-29_00 15 53](https://user-images.githubusercontent.com/7142721/143790273-73d07a93-adc5-44aa-ba28-46eb0105575f.png)
TODO: 
- custom explosion. (still normal one)
- nl_be lang
- custom loot table ?

Conclusion:
Extended Creeper Entity.
Explode function is private won't be overridable. 
Can't suppress Super Tick method entity won't move. (needed for MobEntity)
