### ISSUE TITLE
Register items, blocks and entities like Minecraft

### ISSUE THREAD

**Issue by JoeyDP** [ScicraftLearn/Scicraft#69]
Apparently we don't have to wait for the `onInitialize` call to register things. We can adapt the registration pattern of Minecraft (register in definition) instead of having this code in two places and risking mistakes.

Refactor the existing registrations of items, blocks and entities to follow the design of Minecraft (see source code). Entites will be a bit more tricky because spawns and default attributes need to be registered in dedicated classes.

@pixar02 can you confirm that this is a good practice?

**Comment by pixar02** [comment]
Registering Items/blocks/Entities can be done in a numerous of different ways. 
Could you clarify?

**Comment by JoeyDP** [comment]
Here's an example of Blocks:
![image](https://user-images.githubusercontent.com/2528391/145579301-5083cf1d-bbd2-4c41-a769-8f9133f3e722.png)

To summarize:
- have a `register` function in each 'definition' class like `Blocks` and `Items` and
- call the register function immediately around the `new` statement.

**Comment by pixar02** [comment]
Ooh, that's what you mean.
Honestly it might actually be a coding mistake.
If we forgot to register all the blocks and we would call that Block/Item/... it would be `null`. But if we change it it will never happen. (but we still need a method to call when we `onInitialize`, if we don't "access" the class it won't register)

We should have noticed this sooner since IntelliJ is complaining: 
![image](https://user-images.githubusercontent.com/7142721/145586546-e996767e-f8ea-46c0-bdea-b1f961178c59.png)

**Comment by RobbeNooyens** [comment]
I think that this is what Joey means, so we'd only have to call the constructor with the proper identifier without the need for the registerBlock and registerBlocks method in Blocks.java:

![image](https://user-images.githubusercontent.com/42799452/145587484-a987f8ef-cf62-4729-8b06-89e4ff5cd2d3.png)

Or would this cause the blocks to be null?

**Comment by pixar02** [comment]
Don't know if that would work. 
This is what he meant:
![image](https://user-images.githubusercontent.com/7142721/145590032-bc471874-c9f8-412b-8c46-a4a0ba7ed524.png)

Now when we call `registerBlocks()` it just prints something but the field will register themselfs. If we know that a

**Comment by RobbeNooyens** [comment]
I see, that makes it clear! I've also tested the other method which indeed didn't work

**Comment by JoeyDP** [comment]
I did some searching: you can force the definition classes to be loaded by calling `Class.forName` in our init function.

- https://stackoverflow.com/a/3499322
- https://docs.oracle.com/javase/6/docs/api/java/lang/Class.html#forName(java.lang.String)

**Comment by pixar02** [comment]
> 

Yes, you can do that. But like I said before you always need something to call the classes otherwise it will never be initialized.
