### ISSUE TITLE
Representations for common elements

### ISSUE THREAD

**Issue by RandyParedis** [ScicraftLearn/Scicraft#72]
Create a visualization for the basic atoms, both atom-wise (circle with letter?) and as a collection if possible (e.g., sulfur, silicon...)

- [x] Hydrogen (H)
- [x] Oxygen (O)
- [x] Nitrogen (N)
- [x] Sodium (Na)
- [x] Clorine (Cl)
- [x] Helium (He)
- [x] Carbon (C)
- [x] Neon (Ne)
- [x] Lithium (Li)
- [x] Beryllium (Be)
- [x] Boron (B)
- [x] Fluorine (F)
- [x] Magnesium (Mg)
- [x] Aluminum (Al)
- [x] Silicon (Si)
- [x] Phosphorus (P)
- [x] Sulfur (S)
- [x] Argon (Ar)

Excel with info: https://docs.google.com/spreadsheets/d/1L4H2XjDtrGKZZN532ZQC4TRqk3zfH9b8hjwiufuLPJ8/edit#gid=0
CPK coloring: https://en.wikipedia.org/wiki/CPK_coloring

**Edit:** New representation for atoms, so retry

**Comment by JoeyDP** [comment]
I can only find the first 10 on drive. Could you share the rest?
