### ISSUE TITLE
Potential Extra functionality Entropy Creeper

### ISSUE THREAD

**Issue by pixar02** [ScicraftLearn/Scicraft#8]
Refine Entropy Creeper:
- If the player is in the radius, they also get teleported randomly within a specified range

- Animate the swapping of blocks (don't move all at the same time, but do some moving over the next x ticks.

- A cuboid radius is quite structured which goes against the nature of this mob. Change this to a more chaotic shape, similar to that of an explosion.

- Add a custom sound to the shuffling and perhaps also to replace the 'sizzling' of a Creeper to warm the player.

**Comment by JoeyDP** [comment]
Split into separate issues.
