### ISSUE TITLE
Tier 1: Salt

### ISSUE THREAD

**Issue by RobbeNooyens** [ScicraftLearn/Scicraft#84]
Salt will be represented as the following items:

Salt ore block: 
- drops salt dust when mined
- coal block as placeholder

Salt crystal: 
- grows on salt ore block
- drops salt dust (or crystal item with silk touch)
- amethyst as placeholder

Salt dust: 
- can be placed on the ground
- redstone dust as placeholder

Salt block:
- same recipe as glowstone but with salt dust

References:
- https://docs.google.com/document/d/1znEEGgsLmSSaRPgRKAQrtmq2DzMUrpX7ImWhVG6Gq7Y/edit

**Comment by JoeyDP** [comment]
Split into smaller issues
